### ISSUE TITLE
Typo in learning-another-language/vscode-and-styles

### ISSUE THREAD

**Issue by azbluem** [Ada-Developers-Academy/core-unit-3#102]
There's a typo in the part explaining Prettier config file

Is it supposed to say [javascript] before the code block?

<img width="1050" alt="Screenshot 2022-11-27 at 2 42 44 PM" src="https://user-images.githubusercontent.com/48371317/204163802-4e097412-4131-4891-8e27-d6a733e98918.png">

**Comment by kyra-at-ada** [comment]
Hi, thanks for alerting us to this issue! We currently don't have the ability to manage non-staff opening issues on our Github repos. If you have small typos like this you'd like to see fixed, we'd appreciate you letting us know via this [curriculum feedback form](https://form.asana.com/?k=h4bCndTRb4cUAObmspWA3Q&d=181459410160484) which our curriculum team will review once a quarter. Thank you!
